# Generated by Django 5.2.6 on 2025-09-21 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebShopiApp', '0004_remove_cartmodel_user_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebShopiApp.productsofwebshopi'),
        ),
    ]
