# Generated by Django 5.2.6 on 2025-09-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebShopiApp', '0005_alter_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsofwebshopi',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productsofwebshopi',
            name='brand',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='productsofwebshopi',
            name='category',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='productsofwebshopi',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productsofwebshopi',
            name='reviews',
            field=models.CharField(default='Zero', max_length=200),
        ),
        migrations.AddField(
            model_name='productsofwebshopi',
            name='thumbnail',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='productsofwebshopi',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='productsofwebshopi',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productsofwebshopi',
            name='title',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
