# Generated by Django 5.2.6 on 2025-09-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebShopiApp', '0006_remove_productsofwebshopi_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsofwebshopi',
            name='reviews',
            field=models.CharField(max_length=200),
        ),
    ]
